ecommerce/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # Examples:
    # url(r'^$', 'ecommerce.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^members/', include('members.urls', namespace = 'members')),
    url(r'^items/', include('items.urls', namespace = 'items'))
]

items/urls.py
from django.conf.urls import url
 
from . import views
 
urlpatterns = [
 url(r'^$', views.index, name='index'),
 url(r'^(?P<item_id>[0-9]+)/$', views.show, name='show'),
 url(r'^cart/(?P<item_id>[0-9]+)/add$', views.purchase_item, name='purchase_item'),
 url(r'^cart$', views.cart, name='cart'),
 url(r'^cart/(?P<item_id>[0-9]+)/delete$', views.delete_item, name='delete_item'),
 url(r'^checkout', views.checkout, name='checkout'),
 url(r'^payments', views.payments, name='payments'),
]

members/urls.py
from django.conf.urls import url
 
from . import views
 
urlpatterns = [
 url(r'^$', views.index, name='index'),
 url(r'^signup$', views.signup_form, name='signup'),
 url(r'^register$', views.register, name='register'),
 url(r'^login$', views.login_form, name='login'),
 url(r'^login_user$', views.login_user, name='login_user'),
 url(r'^logout$', views.logout_view, name='logout_view')
]

items/models.py
from django.db import models
from members.views import User

# Create your models here.

class Item(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()
	price = models.FloatField()
	def __str__(self):
		return self.name

class Order(models.Model):
	status = models.IntegerField()
	user = models.ForeignKey(User)
	items = models.ManyToManyField(Item)
	def __str__(self):
		return str(self.id)

members/models.py
from django.db import models
# from members.models import User

# Create your models here.

items/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from .models import Item, Order
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.core import serializers
from django.core.urlresolvers import reverse
from members.views import User



# Create your views here.

def index(request):

	search = request.GET.get('search')
	price_cat = request.GET.get('filter')
	items_list = Item.objects.all()

	if request.user.is_authenticated():
		name = request.user.first_name
	else:
		name = ''

	# put all this shit into hash
	if price_cat=='1':
		items_list = items_list.filter(price__lte=19.99)

	if price_cat=='2':
		items_list = items_list.filter(price__gte=20, price__lte=39.99)

	if price_cat=='3':
		items_list = items_list.filter(price__gte=40, price__lte=59.99)

	if price_cat=='4':
		items_list = items_list.filter(price__gt=59.99)

	if search:
		items_list = items_list.filter(Q(name__icontains=search) | Q(description__icontains=search))

	paginator = Paginator(items_list, 10)
	page = request.GET.get('page')

	try:
		items = paginator.page(page)
	except PageNotAnInteger:
		items = paginator.page(1)
	except EmptyPage:
		items = paginator.page(paginator.num_pages)

	if request.GET.get("format")=="json":
		items = serializers.serialize("json",items)
		return HttpResponse(items, content_type='application/json')

	return render_to_response('items/index.html', {'items': items, 'name':name})

def cart(request):
	orders = Order.objects.filter(user=request.user, status=1)
	if orders:
		order= orders[0]

		items=order.items.all()
		total = 0
		for item in items:
			total += item.price
		return render(request, 'items/cart.html', {'items':items, 'total':total, 'order':order})
	return HttpResponse('empty cart')

def purchase_item(request, item_id):
	if request.user.is_authenticated():

		if request.user.order_set.all():
			orders=request.user.order_set.all()

			if orders.filter(status=1):
				order=orders.filter(status=1)[0]
				order.items.add(Item.objects.get(id=item_id))
				return HttpResponseRedirect(reverse('items:cart'))

			# fix redundancy of else statements below
			else:
				order=Order(status=1, user=request.user)
				order.save()
				order.items.add(Item.objects.get(id=item_id))
				return HttpResponseRedirect(reverse('items:cart'))

		else:
			order=Order(status=1, user=request.user)
			order.save()
			order.items.add(Item.objects.get(id=item_id))
		 	return HttpResponseRedirect(reverse('items:cart'))
			
	return HttpResponseRedirect(reverse('members:login'))

def delete_item(request, item_id):
	order=Order.objects.filter(user=request.user, status=1)[0]
	order.items.remove(Item.objects.get(id=item_id))
	return HttpResponseRedirect(reverse('items:cart'))

def checkout(request):
	order=Order.objects.filter(user=request.user, status=1)[0]
	order.status=2
	order.save()
	return render(request, 'items/checkout.html', {})

def show(request, item_id):
	item = get_object_or_404(Item, pk=item_id)
	return render(request, 'items/show.html', {'item': item})

def payments(request):
	return render(request, 'items/payments.html', {})

members/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse


# Create your views here.

def index(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse('members:login'))
 	return HttpResponseRedirect(reverse('items:index'))

def signup_form(request):
	return render(request, 'members/signup.html', {})

def register(request):
	user = User.objects.create_user(username = request.POST['user_name'], email = request.POST['email'], password = request.POST['password'])
	user.first_name = request.POST['first_name']
	user.last_name = request.POST['last_name']
	user.save()
	user = authenticate(username = request.POST['user_name'], password = request.POST['password'])
	login(request, user)
	# need to redirect instead of render
	return HttpResponseRedirect(reverse('members:index'))

def login_form(request):
	return render(request, 'members/login.html', {})

def login_user(request):
	user = authenticate(username = request.POST['user_name'], password = request.POST['password'])
	if user is not None:
		login(request, user)
		# need to redirect instead of render
		return HttpResponseRedirect(reverse('members:index'))
	return HttpResponseRedirect(reverse('members:login'))

def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('members:login'))

ecommerce/templates/ecommerce/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<!--    <link rel="stylesheet" href="style.css" />
    <title>{% block title %}My amazing site{% endblock %}</title>-->
</head>

<body>
	<h1>E-commerce</h1>	

    <div id="sidebar">
        {% block sidebar %}
	        <form action='/members/login' method='get'>
				{% csrf_token %}
				<input type = "submit" value="Login">
			</form>
			<form action='/members/signup' method='get'>
				{% csrf_token %}
				<input type = "submit" value="Sign up">
			</form>

	<!--        <a href="members/login">Login</a>
	        <a href="members/signup">Sign up</a>
	        <ul>
	            <li><a href="/">Home</a></li>
	            <li><a href="/blog/">Blog</a></li>
	        </ul>-->
        {% endblock %}
<!--    </div>

    <div id="content">-->

        {% block content %}

        {% endblock %}
    </div>
</body>

<footer>
</footer>

</html>

items/templates/items/cart.html
<h1>Shopping Cart</h1>


{% if items %}
	<p> Order number: {{ order.id }}</p>
	{% csrf_token %}
	<ul>
	{% for item in items %}
    	<li><a href="{% url 'items:show' item.id %}">{{ item.name }}</a> ${{ item.price }} <a href="{% url 'items:cart' %}/{{ item.id }}/delete">Remove</a></li>
	{% endfor %}
	</ul>
{% endif %}

<p>Cart total: ${{ total }}</p>

<!--<form action="payments" method="get" value="order">
	{% csrf_token %}
	<input type = "submit" value="Check out">
	<button>Check out</button>
</form>-->
<a href="{% url 'items:payments' %}"><button>Check out</button>
<a href="{% url 'items:index' %}"><button>Back to items</button></a>

items/templates/items/checkout.html
<h1>Check out page</h1>

items/templates/items/index.html
{% extends "ecommerce/base.html" %}
{% block content %}

<h1>Item index page</h1>

<p>Welcome, {{ name }}!</p>

<p>Search or filter by price</p>

<p><a href="{% url 'items:index' %}?filter=1">$0 - $19.99</a></p>
<p><a href="{% url 'items:index' %}?filter=2">$20 - $39.99</a></p>
<p><a href="{% url 'items:index' %}?filter=3">$40 - $59.99</a></p>
<p><a href="{% url 'items:index' %}?filter=4">$60 +</a></p>

<form action="" method="get">
<!--	<input type="hidden" name="filter" value="">-->
	<input type="text" name="search">
	<input type="submit" value="Search">
</form>
<br></br>


{% if items %}
	<!-- {% csrf_token %} -->
	<ul>
	{% for item in items %}
    	<li><a href="{% url 'items:show' item.id %}">{{ item.name }}</a> ${{ item.price }} <a href="{% url 'items:cart' %}/{{ item.id }}/add">Add to cart</a></li>
	{% endfor %}
	</ul>

<div class="pagination">
	<span class="step-links">
		{% if items.has_previous %}
			<a href = "?page={{ items.previous_page_number }}">previous</a>
		{% endif %}

		<span class="current">
			Page {{ items.number }} of {{ items.paginator.num_pages }}.
		</span>

		{% if items.has_next %}
			<a href = "?page={{ items.next_page_number }}">next</a>
		{% endif %}
	</span>
</div>

{% else %}
    <p>There are no items.</p>
{% endif %}

<br></br>
<!--<a href="{% url 'items:cart' %}"><button>My cart</button></a>-->
<form action='/items/cart' method='get'>
	{% csrf_token %}
	<input type = "submit" value="My Cart">
</form>
<form action='/members/logout' method='get'>
	{% csrf_token %}
	<input type = "submit" value="Log out">
<!--	<button>Log out</button>-->
</form>

{% endblock %}

items/templates/items/payments.html
<h1>Payment page</h1>

<form action='checkout' method='post'>
	{% csrf_token %}
	<p>Credit card number:</p>
	<input name = 'payment'>
	<br></br>
<!--	<button>Sign up</button>-->
	<input type = "submit" value = "Place Order">
</form>

items/templates/items/show.html
<h1>Item Page</h1>

<p>Item: {{ item.name }}</p>

<p>Item number: {{ item.id }}</p>

<p>Price: {{ item.price }}</p>

<p>Description: {{ item.description}}</p>

<a href="{% url 'items:index' %}"><button>Back to index</button></a>

<!-- <form action='index' method='get'>
	{% csrf_token %}
	<button>Back to index</button>
</form> -->

members/templates/members/index.html
<h1>User Index Page</h1>

<p>You're logged in.</p>

<form action='logout' method='post'>
	{% csrf_token %}
	<input type = "submit" value="Log out">
<!--	<button>Log out</button>-->
</form>

members/templates/members/login.html
<h1>Log in page</h1>
<p>You are not logged in.</p>

<form action='login_user' method='post'>
	{% csrf_token %}
	<p>User name:</p>
	<input name = 'user_name'>
	<p>Password:</p>
	<input name = 'password'>
	<br></br>
<!--	<button>Log in</button>-->
	<input type = "submit" value="Log in">
</form>

<a href="{% url 'members:signup' %}"><button>Register new user</button></a>

<!-- <form action='signup' method='get'>
	{% csrf_token %}
	<button>Register new user</button>
</form> -->

members/templates/members/signup.html
<h1>Sign up form</h1>
<form action='register' method='post'>
	{% csrf_token %}
	<p>First Name:</p>
	<input name = 'first_name'>
	<p>Last Name:</p>
	<input name = 'last_name'>
	<p>E-mail:</p>
	<input name = 'email'>
	<p>User Name:</p>
	<input name = 'user_name'>
	<p>Password:</p>
	<input name = 'password'>
	<br></br>
<!--	<button>Sign up</button>-->
	<input type = "submit" value = "Sign up">
</form>